from .transactions import router as transactions_router
from .accounts import router as accounts_router
from .wishlist import router as wishlist_router
from .investments import router as investments_router
from .categories import router as categories_router
from .dashboard import router as dashboard_router
from .settings import router as settings_router
from .import_export import router as import_router
from .llm import router as llm_router
from .subscriptions import router as subscriptions_router
